<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../../src/YueYinqiu.HpcRegistrar/YueYinqiu.HpcRegistrar.csproj" />
      <ProjectReference Include="../YueYinqiu.HpcRegistrar.E2E/YueYinqiu.HpcRegistrar.E2E.csproj" />
    </ItemGroup>

</Project>
